<?php

use Illuminate\Database\Seeder;

class VehiclesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('vehicles')->insert([
                ['manufacturer_id' => '1', 'vehiclemodel_id' => '1', 'type' => 'electric', 'usage' => 'personal', 'license_plate' => 'HH14 PCH', 'weight_category' => '6', 'no_seats' => '2', 'has_boot' => '0', 'has_trailer' => '0', 'owner_id' => '1', 'transmission' => 'manual', 'colour_id' => '1', 'is_hgv' => '1', 'no_doors' => '3', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '2', 'engine_cc' => '2752', 'fuel_type' => 'electric',],
                ['manufacturer_id' => '2', 'vehiclemodel_id' => '2', 'type' => 'hybrid', 'usage' => 'business', 'license_plate' => 'NX02 XKR', 'weight_category' => '2', 'no_seats' => '3', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '2', 'transmission' => 'semi-automatic', 'colour_id' => '2', 'is_hgv' => '0', 'no_doors' => '2', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '5', 'engine_cc' => '1877', 'fuel_type' => 'diesel',],
                ['manufacturer_id' => '2', 'vehiclemodel_id' => '3', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'YD15 QWK', 'weight_category' => '27', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '3', 'transmission' => 'semi-automatic', 'colour_id' => '3', 'is_hgv' => '0', 'no_doors' => '1', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '10', 'engine_cc' => '2023', 'fuel_type' => 'petrol',],
                ['manufacturer_id' => '1', 'vehiclemodel_id' => '4', 'type' => 'diesel', 'usage' => 'business', 'license_plate' => 'ON08 VBC', 'weight_category' => '33', 'no_seats' => '5', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '4', 'transmission' => 'semi-automatic', 'colour_id' => '4', 'is_hgv' => '0', 'no_doors' => '1', 'sunroof' => '0', 'has_gps' => '0', 'no_wheels' => '12', 'engine_cc' => '2856', 'fuel_type' => 'diesel',],
                ['manufacturer_id' => '3', 'vehiclemodel_id' => '5', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'GW13 JNH', 'weight_category' => '14', 'no_seats' => '2', 'has_boot' => '0', 'has_trailer' => '1', 'owner_id' => '5', 'transmission' => 'automatic', 'colour_id' => '5', 'is_hgv' => '0', 'no_doors' => '0', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '4', 'engine_cc' => '2841', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '3', 'vehiclemodel_id' => '6', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'SE02 CTN', 'weight_category' => '18', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '6', 'transmission' => 'semi-automatic', 'colour_id' => '6', 'is_hgv' => '0', 'no_doors' => '3', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '9', 'engine_cc' => '974', 'fuel_type' => 'electric',],
                ['manufacturer_id' => '4', 'vehiclemodel_id' => '7', 'type' => 'electric', 'usage' => 'business', 'license_plate' => 'RI16 AMH', 'weight_category' => '5', 'no_seats' => '2', 'has_boot' => '0', 'has_trailer' => '0', 'owner_id' => '7', 'transmission' => 'manual', 'colour_id' => '7', 'is_hgv' => '0', 'no_doors' => '0', 'sunroof' => '1', 'has_gps' => '0', 'no_wheels' => '12', 'engine_cc' => '2916', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '5', 'vehiclemodel_id' => '8', 'type' => 'diesel', 'usage' => 'business', 'license_plate' => 'FP06 SQT', 'weight_category' => '34', 'no_seats' => '4', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '8', 'transmission' => 'automatic', 'colour_id' => '8', 'is_hgv' => '0', 'no_doors' => '4', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '2', 'engine_cc' => '2391', 'fuel_type' => 'diesel',],
                ['manufacturer_id' => '5', 'vehiclemodel_id' => '9', 'type' => 'petrol', 'usage' => 'business', 'license_plate' => 'LL05 LJZ', 'weight_category' => '12', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '1', 'owner_id' => '9', 'transmission' => 'semi-automatic', 'colour_id' => '9', 'is_hgv' => '0', 'no_doors' => '2', 'sunroof' => '1', 'has_gps' => '1', 'no_wheels' => '8', 'engine_cc' => '2455', 'fuel_type' => 'electric',],
                ['manufacturer_id' => '6', 'vehiclemodel_id' => '10', 'type' => 'diesel', 'usage' => 'personal', 'license_plate' => 'YR07 BZV', 'weight_category' => '22', 'no_seats' => '5', 'has_boot' => '0', 'has_trailer' => '1', 'owner_id' => '10', 'transmission' => 'automatic', 'colour_id' => '10', 'is_hgv' => '0', 'no_doors' => '1', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '2', 'engine_cc' => '2185', 'fuel_type' => 'diesel',],
                ['manufacturer_id' => '1', 'vehiclemodel_id' => '11', 'type' => 'petrol', 'usage' => 'business', 'license_plate' => 'PP02 QIF', 'weight_category' => '18', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '1', 'owner_id' => '11', 'transmission' => 'semi-automatic', 'colour_id' => '11', 'is_hgv' => '0', 'no_doors' => '1', 'sunroof' => '1', 'has_gps' => '1', 'no_wheels' => '11', 'engine_cc' => '2124', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '5', 'vehiclemodel_id' => '11', 'type' => 'hybrid', 'usage' => 'business', 'license_plate' => 'MG09 PTF', 'weight_category' => '23', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '12', 'transmission' => 'semi-automatic', 'colour_id' => '12', 'is_hgv' => '0', 'no_doors' => '2', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '6', 'engine_cc' => '937', 'fuel_type' => 'petrol',],
                ['manufacturer_id' => '6', 'vehiclemodel_id' => '12', 'type' => 'electric', 'usage' => 'business', 'license_plate' => 'YP05 XSR', 'weight_category' => '39', 'no_seats' => '3', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '13', 'transmission' => 'manual', 'colour_id' => '13', 'is_hgv' => '0', 'no_doors' => '2', 'sunroof' => '0', 'has_gps' => '0', 'no_wheels' => '2', 'engine_cc' => '2995', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '7', 'vehiclemodel_id' => '13', 'type' => 'diesel', 'usage' => 'personal', 'license_plate' => 'YP05 GJF', 'weight_category' => '20', 'no_seats' => '5', 'has_boot' => '0', 'has_trailer' => '1', 'owner_id' => '14', 'transmission' => 'manual', 'colour_id' => '14', 'is_hgv' => '0', 'no_doors' => '0', 'sunroof' => '1', 'has_gps' => '1', 'no_wheels' => '4', 'engine_cc' => '1480', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '8', 'vehiclemodel_id' => '14', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'GP15 KZM', 'weight_category' => '21', 'no_seats' => '3', 'has_boot' => '1', 'has_trailer' => '1', 'owner_id' => '15', 'transmission' => 'semi-automatic', 'colour_id' => '15', 'is_hgv' => '0', 'no_doors' => '0', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '12', 'engine_cc' => '2987', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '9', 'vehiclemodel_id' => '15', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'SL17 TDU', 'weight_category' => '40', 'no_seats' => '4', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '16', 'transmission' => 'manual', 'colour_id' => '16', 'is_hgv' => '0', 'no_doors' => '3', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '9', 'engine_cc' => '2558', 'fuel_type' => 'electric',],
                ['manufacturer_id' => '9', 'vehiclemodel_id' => '4', 'type' => 'petrol', 'usage' => 'business', 'license_plate' => 'NW13 OBN', 'weight_category' => '28', 'no_seats' => '5', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '17', 'transmission' => 'manual', 'colour_id' => '17', 'is_hgv' => '1', 'no_doors' => '3', 'sunroof' => '1', 'has_gps' => '1', 'no_wheels' => '7', 'engine_cc' => '2836', 'fuel_type' => 'duel',],
                ['manufacturer_id' => '10', 'vehiclemodel_id' => '2', 'type' => 'hybrid', 'usage' => 'personal', 'license_plate' => 'DC13 ACY', 'weight_category' => '10', 'no_seats' => '3', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '18', 'transmission' => 'semi-automatic', 'colour_id' => '18', 'is_hgv' => '0', 'no_doors' => '1', 'sunroof' => '1', 'has_gps' => '1', 'no_wheels' => '12', 'engine_cc' => '1270', 'fuel_type' => 'diesel',],
                ['manufacturer_id' => '11', 'vehiclemodel_id' => '16', 'type' => 'petrol', 'usage' => 'personal', 'license_plate' => 'GG05 IEL', 'weight_category' => '12', 'no_seats' => '2', 'has_boot' => '1', 'has_trailer' => '0', 'owner_id' => '19', 'transmission' => 'semi-automatic', 'colour_id' => '19', 'is_hgv' => '0', 'no_doors' => '3', 'sunroof' => '0', 'has_gps' => '1', 'no_wheels' => '2', 'engine_cc' => '1835', 'fuel_type' => 'duel']
            ]);
    }

}
